FROM ubuntu:18.04

LABEL maintaner="Alikhan M. (alikhan.murzayev@gmail.com)"

ENV LC_ALL C.UTF-8

ENV LANG C.UTF-8

# install python3.7 and pip3
RUN apt-get update && apt-get install -y \
    python3.7-dev \
    python3-pip \
